[build]
  publish = "/"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For SPA routing
[[redirects]]
  from = "/server"
  to = "/.netlify/functions/server"
  status = 200